/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/services-mock/utils.ts                                                         ***/

import {
    DN_LIST,
} from '../boot/diagramMockData'



export function randomInt(x: number) : number
{
    return Math.floor(Math.random() * x);
}

export function getRandomDnList()
{
    const count = randomInt(10) + 3;
    const res : string[] = [];

    for(let i = 0; i < count; i++)
    {
        const dn = (<string[]>DN_LIST)[randomInt(DN_LIST.length)];
        res.push(dn)
    }
    return res;
}
