/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../backend.git/src/index.ts                                                                  ***/

import { Backend } from '@kubevious/helper-backend'
import { Context } from './context'

const backend = new Backend("backend");

backend.initialize(() => {
    const context = new Context(backend);
    return context.run();
});
