kind: Deployment
apiVersion: apps/v1
metadata:
  name: logger
  namespace: test-webapp-backend
  labels:
    app: logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: nginx
          image: nginx
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst