/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/Summary/index.js                                                ***/

import React from 'react'
import BaseComponent from '../../HOC/BaseComponent'
import PropertiesContents from '../Properties/PropertiesContents'
import './styles.scss'
import { isEmptyObject } from '../../utils/util'

class Summary extends BaseComponent {
    constructor(props) {
        super(props)

        this.state = {
            data: {},
        }
    }

    componentDidMount() {
        this.subscribeToSharedState('summary', (data) => {
            this.setState({ data })
        })
    }

    render() {
        const { data } = this.state
        if (!isEmptyObject(data)) {
            return (
                <div id="summaryComponent" className="summary">
                    {Object.values(data).map((block) => (
                        <div className="summary-container" key={block.id}>
                            <label>{block.title}</label>
                            <div className="summary-container-inner">
                                <PropertiesContents group={block} />
                            </div>
                        </div>
                    ))}
                </div>
            )
        }
        return <div className="loading-placeholder">Loading...</div>
    }
}

export default Summary
