/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/Properties/PropertiesCounters/index.js                          ***/

import React from 'react'
import './styles.scss'

import PropertiesValue from '../helpers'

const PropertiesCounters = ({ config }) => {
    return (
        <div className="counters-container">
            {config.map(element => (
                <div className="counter-block" key={element.title}>
                    <label>{element.title}</label>
                    <div className="counter-value">
                        {PropertiesValue(element)}
                    </div>
                </div>
            ))}
        </div>
    )
}

export default PropertiesCounters
