/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/Popup/index.js                                                  ***/

import React from 'react'
import BaseComponent from '../../HOC/BaseComponent'

import './styles.scss'


class Popup extends BaseComponent {
    constructor(props) {
        super(props)
  
        this.closePopup = this.closePopup.bind(this);
    }

    closePopup() {
        this.sharedState.set('popup_window', null);
    }
  
    render() {
        return (
            <div id="popup" className="popup">
                <div className="popup-contents">
                    {this.props.popupContent}
                </div>
                <button className="close" onClick={this.closePopup}/>
            </div>
        )
    }
}

export default Popup
