/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/Popup/index.js                                                  ***/

import React from 'react'

import './styles.scss'

const Popup = ({ children, closePopup }) => {
    return (
        <div id="popup" className="popup">
            <div className="popup-contents">
                {children}
            </div>
            <button className="close" onClick={closePopup}/>
        </div>
    )
}

export default Popup
