/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/CopyClipboard/index.js                                          ***/

import React, { useState } from 'react'
import { faClone as farClone } from '@fortawesome/free-regular-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import './styles.scss'

const CopyClipboard = ({ text }) => {
    const [copied, setCopied] = useState(false)

    const copyText = () => {
        const textField = document.createElement('textarea')
        textField.value = text
        document.body.appendChild(textField)
        textField.select()
        document.execCommand('copy')
        setCopied(true)
        textField.remove()

        setTimeout(() => {
            setCopied(false)
        }, 3000)
    }

    return (
        <div className='icon-wrapper'>
            {copied && (
                <div className='copied-container'>
                    Copied to clipboard
                    <div className='caret' />
                </div>
            )}

            <FontAwesomeIcon
                className='copy-icon'
                icon={farClone}
                onClick={() => copyText()}
                title='Copy to clipboard'
            />
        </div>
    )
}

export default CopyClipboard
