/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/Properties/PropertiesObjectList/index.js                        ***/

import React from 'react'
import { DnShortcutComponent } from '@kubevious/ui-components';

const PropertiesObjectList = ({ config }) => {
    return (
        <>
            {config.map((element) => (
                <div key={element.dn}>
                    <DnShortcutComponent
                        dn={element.dn}
                        errors={element.alertCount.error}
                        warnings={element.alertCount.warn}
                    />
                </div>
            ))}
        </>
    )
}

export default PropertiesObjectList
