/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/Events/index.tsx                                                ***/

import React, { PureComponent } from "react"

export class Events extends PureComponent {
    render() {
        return <div>Events</div>
    }
}
