/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../parser/src/lib/logic/polishers/010_namespace.js                                           ***/

const _ = require("the-lodash");

module.exports = {
    target: {
        path: ["ns"]
    },

    order: 10,

    handler: ({scope, item, logger}) =>
    {
        var namespaceScope = scope.getNamespaceScope(item.naming);

        var properties = {
            "Applications": namespaceScope.appCount,
            "Ingresses": namespaceScope.items.count('Ingress'),
            "Secrets": namespaceScope.items.count('Secret')
        }

        item.addProperties({
            kind: "key-value",
            id: "properties",
            title: "Properties",
            order: 5,
            config: properties
        });  
    }
}