/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/utils/ui-utils.ts                                                          ***/

import _ from "the-lodash"
import {
    prettyKind as helperPrettyKind,
} from "@kubevious/helpers/dist/docs"

export const prettyKind = (kind: string): string => {
    let value = helperPrettyKind(kind)
    if (!value) {
        value = _.upperFirst(kind)
    }
    return value
}
