/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/UiLogs/index.js                                                 ***/

import React, { PureComponent } from 'react'

class UiLogs extends PureComponent {
    render() {
        return <div>UI Logs</div>
    }
}

export default UiLogs
