/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/Properties/KeyValueList/index.js                                ***/

import _ from 'the-lodash'
import React from 'react'

import './styles.scss'

import PropertiesValue from '../helpers'

const KeyValueList = ({ config }) => {
    return (
        <div className="KeyValueList-container">
            {config &&
                Object.entries(config).map((item, index) => (
                    <div className="env-variable" key={index}>
                        <div className="name">{item[0]}:</div>
                        <div className="value">{PropertiesValue(item[1])}</div>
                    </div>
                ))}
        </div>
    )
}

export default KeyValueList
