/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui/src/src/services/DiagramService.js                                                     ***/

class DiagramService {

    constructor(client)
    {
        this._client = client;
    }

    fetchDiagram(cb) {
        return this._client.get('/tree')
            .then(result => {
                cb(result.data);
            })
    }

    fetchAssets(dn, cb) {
        return this._client.get('/assets', { dn: dn })
            .then(result => {
                cb(result.data);
            })
    }

    fetchSearchResults(criteria, cb) {
        return this._client.get('/search', { criteria: criteria })
            .then(result => {
                cb(result.data);
            })
    }
}

export default DiagramService
