/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/services/MiscService.js                                                    ***/

class MiscService {

    constructor(client)
    {
        this._client = client;
    }

    fetchAbout(cb) {
        var info = {
            version: require('../version')
        }
                  
        return Promise.resolve()
            .then(() => {
                return this._client.get('/version')
                    .then(result => {
                        info['backend version'] = result.data.version;
                    })
                    .catch(reason => {
                        info['backend version'] = "unknown";
                    });
            })
            .then(() => {
                cb(info);
            });
  
    }
}

export default MiscService
