/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../parser.git/src/lib/logic/parsers/040_service.js                                           ***/

const _ = require("the-lodash");

module.exports = {
    target: {
        api: "v1",
        kind: "Service"
    },

    kind: "service",

    order: 40,

    needNamespaceScope: true,

    handler: ({scope, item, createK8sItem, createAlert, hasCreatedItems, namespaceScope}) =>
    {
        var serviceScope = namespaceScope.items.register(item.config);

        var appSelector = _.get(item.config, 'spec.selector');
        if (appSelector)
        {
            var appScopes = namespaceScope.findAppScopesByLabels(appSelector);
            for(var appScope of appScopes)
            {
                serviceScope.associateAppScope(appScope);

                appScope.properties['Exposed'] = 'With Service';

                var appItem = appScope.item;

                var serviceItemName = item.config.spec.type;
                var serviceCount = appItem.getChildrenByKind('service')
                    .filter(x => x.config.spec.type == serviceItemName)
                    .length;
                if (serviceCount != 0) {
                    serviceItemName += " " + (serviceCount + 1);
                }
                createService(appItem, { name: serviceItemName, order: 200 });
                
                var portsConfig = _.get(item.config, 'spec.ports');
                if (portsConfig) {
                    for(var portConfig of portsConfig) {      
                        var appPort = portConfig.targetPort;                   
                        var appPortInfo = appScope.ports[appPort];
                        if (appPortInfo) {
                            createService(appPortInfo.portItem, { name: serviceItemName })
                        } else {
                            createAlert('Port-' + appPort, 'warn', 'Missing port ' + appPort + ' definition.');
                        }
                    }
                }
            }

            if (appScopes.length == 0) {
                createAlert('MissingApp', 'error', 'Could not find apps matching selector.');
            } else if (appScopes.length > 1) {
                createAlert('MultipleApps', 'warn', 'More than one apps matched selector.');
            }
        }
        else
        {
            // createAlert('MissingSelector', 'error', 'Missing selector.');
        }

        if (!hasCreatedItems()) {
            var rawContainer = scope.fetchRawContainer(item, "Services");
            createService(rawContainer);
        }

        /*** HELPERS ***/
        function createService(parent, params)
        {
            var k8sService = createK8sItem(parent, params);
            serviceScope.registerItem(k8sService);
            return k8sService;
        }

    }
}