/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/Notifications/types.ts                                          ***/

import { Question } from "../Feedback/types"

export type RequestList = {
    kind: string
    id?: string
    name?: string
    questions?: Question[]
    title?: string
    content?: string
    version?: string
    url?: string
    changes?: string[]
    features?: string[]
    request?: RequestList
}

export type NotificationsState = {
    list: RequestList[]
}
