/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/components/SEO/index.tsx                                                       ***/

import React from "react"
import { Helmet } from "react-helmet"

export const SEO = () => {
    return <Helmet></Helmet>
}
