/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui.git/src/src/components/SEO/index.js                                                    ***/

import React from 'react'
import { Helmet } from 'react-helmet'

const SEO = () => {
    return <Helmet></Helmet>
}

export default SEO
