#!/bin/bash
MY_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
MY_DIR="$(dirname "$MY_PATH")"
cd $MY_DIR/../..

SRC_FOLDER=$1
DEST_FOLDER=$2

SRC_FOLDER="ui/src${SRC_FOLDER}"
DEST_FOLDER="portable/src/client${DEST_FOLDER}"

if [ -d "${DEST_FOLDER}" ]; then
  echo "Folder exists"
else
  echo "Folder not exist"
  mkdir -p "${DEST_FOLDER}"
fi

cp -r "${SRC_FOLDER}"/* "${DEST_FOLDER}"

DEST_FOLDER="${DEST_FOLDER}/*"

for f in $DEST_FOLDER; do
  if [[ ${f} == *.js ]]; then
    echo "    Javascript Source"
    sed -i '1s/^/\/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED ***\/ \n/' "$f"
    sed -i '2s/^/\/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI. ***\/ \n/' "$f"
    sed -i '3s/^/ \n /' "$f"
  elif [[ ${f} == *css ]]; then
    echo "    CSS Source"
    sed -i '1s/^/\/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED ***\/ \n/' "$f"
    sed -i '2s/^/\/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI. ***\/ \n/' "$f"
    sed -i '3s/^/ \n /' "$f"
  fi
done


# example of script run
# ./copy-folder.sh "/src/components/About" "/src/components/About"
