apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"kubevious-pods-fetcher","namespace":"book"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"pods-fetcher"},"subjects":[{"kind":"ServiceAccount","name":"kubevious-parser","namespace":"kubevious"}]}
    creationTimestamp: "2020-04-10T23:48:47Z"
    name: kubevious-pods-fetcher
    namespace: book
    resourceVersion: "37201928"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/book/rolebindings/kubevious-pods-fetcher
    uid: d22dd5c0-7b85-11ea-bb1c-42010a800057
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: pods-fetcher
  subjects:
  - kind: ServiceAccount
    name: kubevious-parser
    namespace: kubevious
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2020-01-18T00:43:51Z"
    labels:
      app: certmanager-issuer
      chart: certmanager-issuer-0.1.0
      heritage: Helm
      release: gitlab
    name: gitlab-certmanager-issuer
    namespace: gitlab
    resourceVersion: "2016227"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/gitlab/rolebindings/gitlab-certmanager-issuer
    uid: 991779d1-398b-11ea-b115-42010a8001d6
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: gitlab-certmanager-issuer
  subjects:
  - kind: ServiceAccount
    name: gitlab-certmanager-issuer
    namespace: gitlab
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2020-01-18T00:43:51Z"
    labels:
      app: gitlab-gitlab-runner
      chart: gitlab-runner-0.12.0
      heritage: Helm
      release: gitlab
    name: gitlab-gitlab-runner
    namespace: gitlab
    resourceVersion: "2016226"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/gitlab/rolebindings/gitlab-gitlab-runner
    uid: 991787a2-398b-11ea-b115-42010a8001d6
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: gitlab-gitlab-runner
  subjects:
  - kind: ServiceAccount
    name: gitlab-gitlab-runner
    namespace: gitlab
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2020-01-18T00:43:51Z"
    labels:
      app: nginx-ingress
      chart: nginx-ingress-0.30.0-1
      heritage: Helm
      release: gitlab
    name: gitlab-nginx-ingress
    namespace: gitlab
    resourceVersion: "2016225"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/gitlab/rolebindings/gitlab-nginx-ingress
    uid: 99162521-398b-11ea-b115-42010a8001d6
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: gitlab-nginx-ingress
  subjects:
  - kind: ServiceAccount
    name: gitlab-nginx-ingress
    namespace: gitlab
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2020-01-18T00:43:51Z"
    labels:
      app: redis
      chart: redis-ha-0.1.0
      heritage: Helm
      release: gitlab
    name: gitlab-redis
    namespace: gitlab
    resourceVersion: "2016224"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/gitlab/rolebindings/gitlab-redis
    uid: 9915e51a-398b-11ea-b115-42010a8001d6
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: gitlab-redis
  subjects:
  - kind: ServiceAccount
    name: gitlab-redis
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-public
    resourceVersion: "147"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-public/rolebindings/system%3Acontroller%3Abootstrap-signer
    uid: b060e0fc-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:bootstrap-signer
  subjects:
  - kind: ServiceAccount
    name: bootstrap-signer
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"fluentd-gcp-scaler-binding","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"system:fluentd-gcp-scaler"},"subjects":[{"kind":"ServiceAccount","name":"fluentd-gcp-scaler","namespace":"kube-system"}]}
    creationTimestamp: "2020-01-11T06:01:02Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: fluentd-gcp-scaler-binding
    namespace: kube-system
    resourceVersion: "361"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/fluentd-gcp-scaler-binding
    uid: bf358f76-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:fluentd-gcp-scaler
  subjects:
  - kind: ServiceAccount
    name: fluentd-gcp-scaler
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"gce:cloud-provider","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"gce:cloud-provider"},"subjects":[{"kind":"ServiceAccount","name":"cloud-provider","namespace":"kube-system"}]}
    creationTimestamp: "2020-01-11T06:01:14Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
    name: gce:cloud-provider
    namespace: kube-system
    resourceVersion: "500"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/gce%3Acloud-provider
    uid: c6425934-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: gce:cloud-provider
  subjects:
  - kind: ServiceAccount
    name: cloud-provider
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"gce:podsecuritypolicy:calico-sa","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"gce:podsecuritypolicy:privileged"},"subjects":[{"kind":"ServiceAccount","name":"calico-sa","namespace":"kube-system"}]}
    creationTimestamp: "2020-01-22T17:44:02Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: gce:podsecuritypolicy:calico-sa
    namespace: kube-system
    resourceVersion: "4122760"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/gce%3Apodsecuritypolicy%3Acalico-sa
    uid: c733ca80-3d3e-11ea-96d3-42010a80017a
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: gce:podsecuritypolicy:privileged
  subjects:
  - kind: ServiceAccount
    name: calico-sa
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2020-01-18T00:43:52Z"
    labels:
      app: webhook
      app.kubernetes.io/instance: gitlab
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: webhook
      helm.sh/chart: certmanager-v0.10.1
    name: gitlab-cert-manager-webhook:webhook-authentication-reader
    namespace: kube-system
    resourceVersion: "2016228"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/gitlab-cert-manager-webhook%3Awebhook-authentication-reader
    uid: 991abff7-398b-11ea-b115-42010a8001d6
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - kind: ServiceAccount
    name: gitlab-cert-manager-webhook
    namespace: gitlab
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"heapster-binding","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"system:pod-nanny"},"subjects":[{"kind":"ServiceAccount","name":"heapster","namespace":"kube-system"}]}
    creationTimestamp: "2020-01-11T06:01:02Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: heapster-binding
    namespace: kube-system
    resourceVersion: "364"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/heapster-binding
    uid: bf443d2e-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:pod-nanny
  subjects:
  - kind: ServiceAccount
    name: heapster
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"metrics-server-auth-reader","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"extension-apiserver-authentication-reader"},"subjects":[{"kind":"ServiceAccount","name":"metrics-server","namespace":"kube-system"}]}
    creationTimestamp: "2020-01-11T06:01:02Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: metrics-server-auth-reader
    namespace: kube-system
    resourceVersion: "398"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/metrics-server-auth-reader
    uid: bf90aaf5-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-03-26T11:50:14Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::extension-apiserver-authentication-reader
    namespace: kube-system
    resourceVersion: "31420226"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system%3A%3Aextension-apiserver-authentication-reader
    uid: f4beb699-6f57-11ea-8ebf-42010a800207
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-controller-manager
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-scheduler
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-controller-manager
    namespace: kube-system
    resourceVersion: "31420227"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system%3A%3Aleader-locking-kube-controller-manager
    uid: b053bfdf-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system::leader-locking-kube-controller-manager
  subjects:
  - kind: ServiceAccount
    name: kube-controller-manager
    namespace: kube-system
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-controller-manager
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-scheduler
    namespace: kube-system
    resourceVersion: "31420228"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system%3A%3Aleader-locking-kube-scheduler
    uid: b0569337-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system::leader-locking-kube-scheduler
  subjects:
  - kind: ServiceAccount
    name: kube-scheduler
    namespace: kube-system
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-scheduler
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-system
    resourceVersion: "144"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system%3Acontroller%3Abootstrap-signer
    uid: b058e738-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:bootstrap-signer
  subjects:
  - kind: ServiceAccount
    name: bootstrap-signer
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:cloud-provider
    namespace: kube-system
    resourceVersion: "145"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system%3Acontroller%3Acloud-provider
    uid: b05b8b9a-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:cloud-provider
  subjects:
  - kind: ServiceAccount
    name: cloud-provider
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:token-cleaner
    namespace: kube-system
    resourceVersion: "146"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system%3Acontroller%3Atoken-cleaner
    uid: b05e938f-3437-11ea-9cdc-42010a8001cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:token-cleaner
  subjects:
  - kind: ServiceAccount
    name: token-cleaner
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"typha-cpha","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"typha-cpha"},"subjects":[{"kind":"ServiceAccount","name":"typha-cpha","namespace":"kube-system"}]}
    creationTimestamp: "2020-01-22T17:44:03Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: typha-cpha
    namespace: kube-system
    resourceVersion: "4122824"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/typha-cpha
    uid: c794ab23-3d3e-11ea-96d3-42010a80017a
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: typha-cpha
  subjects:
  - kind: ServiceAccount
    name: typha-cpha
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2020-01-18T00:05:48Z"
    labels:
      app: openfaas
      chart: openfaas-5.4.1
      component: faas-controller
      heritage: Helm
      release: openfaas
    name: openfaas-controller
    namespace: openfaas-fn
    resourceVersion: "2007023"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/openfaas-fn/rolebindings/openfaas-controller
    uid: 483f2893-3986-11ea-b115-42010a8001d6
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: openfaas-controller
  subjects:
  - kind: ServiceAccount
    name: openfaas-controller
    namespace: openfaas
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2020-01-18T00:05:48Z"
    labels:
      app: openfaas
      chart: openfaas-5.4.1
      component: prometheus
      heritage: Helm
      release: openfaas
    name: openfaas-prometheus
    namespace: openfaas
    resourceVersion: "2007024"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/openfaas/rolebindings/openfaas-prometheus
    uid: 484052dd-3986-11ea-b115-42010a8001d6
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: openfaas-prometheus
  subjects:
  - kind: ServiceAccount
    name: openfaas-prometheus
    namespace: openfaas
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
