apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2020-01-18T00:43:51Z"
    name: gitlab-certmanager-issuer
    namespace: gitlab
    resourceVersion: "2016223"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/gitlab/roles/gitlab-certmanager-issuer
    uid: 9907cb28-398b-11ea-b115-42010a8001d6
  rules:
  - apiGroups:
    - certmanager.k8s.io
    resources:
    - issuers
    verbs:
    - get
    - list
    - update
    - create
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2020-01-18T00:43:51Z"
    labels:
      app: gitlab-gitlab-runner
      chart: gitlab-runner-0.12.0
      heritage: Helm
      release: gitlab
    name: gitlab-gitlab-runner
    namespace: gitlab
    resourceVersion: "2016221"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/gitlab/roles/gitlab-gitlab-runner
    uid: 99078302-398b-11ea-b115-42010a8001d6
  rules:
  - apiGroups:
    - ""
    resources:
    - '*'
    verbs:
    - '*'
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2020-01-18T00:43:51Z"
    labels:
      app: nginx-ingress
      chart: nginx-ingress-0.30.0-1
      heritage: Helm
      release: gitlab
    name: gitlab-nginx-ingress
    namespace: gitlab
    resourceVersion: "2016222"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/gitlab/roles/gitlab-nginx-ingress
    uid: 9907bacd-398b-11ea-b115-42010a8001d6
  rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - configmaps
    - pods
    - secrets
    - endpoints
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - update
    - watch
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - ingresses/status
    verbs:
    - update
  - apiGroups:
    - ""
    resourceNames:
    - ingress-controller-leader-gitlab-nginx
    resources:
    - configmaps
    verbs:
    - get
    - update
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - create
    - get
    - update
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2020-01-18T00:43:51Z"
    labels:
      app: redis
      chart: redis-ha-0.1.0
      heritage: Helm
      release: gitlab
    name: gitlab-redis
    namespace: gitlab
    resourceVersion: "2016220"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/gitlab/roles/gitlab-redis
    uid: 9907d6ec-398b-11ea-b115-42010a8001d6
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-public
    resourceVersion: "141"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-public/roles/system%3Acontroller%3Abootstrap-signer
    uid: b050439e-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - cluster-info
    resources:
    - configmaps
    verbs:
    - update
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{"kubernetes.io/deprecation":"cloud-provider role is DEPRECATED in the concern of potential collisions and will be removed in 1.16. Do not use this role."},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"cloud-provider","namespace":"kube-system"},"rules":[{"apiGroups":[""],"resources":["configmaps"],"verbs":["create","get","patch","update","list","watch"]}]}
      kubernetes.io/deprecation: cloud-provider role is DEPRECATED in the concern
        of potential collisions and will be removed in 1.16. Do not use this role.
    creationTimestamp: "2020-01-11T06:01:14Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
    name: cloud-provider
    namespace: kube-system
    resourceVersion: "504"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/cloud-provider
    uid: c64a080f-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - get
    - patch
    - update
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: extension-apiserver-authentication-reader
    namespace: kube-system
    resourceVersion: "135"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/extension-apiserver-authentication-reader
    uid: b026684d-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - extension-apiserver-authentication
    resources:
    - configmaps
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"gce:cloud-provider","namespace":"kube-system"},"rules":[{"apiGroups":[""],"resources":["configmaps"],"verbs":["create","get","patch","update","list","watch"]}]}
    creationTimestamp: "2020-01-11T06:01:14Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
    name: gce:cloud-provider
    namespace: kube-system
    resourceVersion: "502"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/gce%3Acloud-provider
    uid: c64499bd-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - get
    - patch
    - update
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-controller-manager
    namespace: kube-system
    resourceVersion: "139"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/system%3A%3Aleader-locking-kube-controller-manager
    uid: b04ab9c9-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - kube-controller-manager
    resources:
    - configmaps
    verbs:
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-scheduler
    namespace: kube-system
    resourceVersion: "140"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/system%3A%3Aleader-locking-kube-scheduler
    uid: b04da62d-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - kube-scheduler
    resources:
    - configmaps
    verbs:
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-system
    resourceVersion: "136"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/system%3Acontroller%3Abootstrap-signer
    uid: b029e74f-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:cloud-provider
    namespace: kube-system
    resourceVersion: "137"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/system%3Acontroller%3Acloud-provider
    uid: b043ee80-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-11T06:00:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:token-cleaner
    namespace: kube-system
    resourceVersion: "138"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/system%3Acontroller%3Atoken-cleaner
    uid: b0479966-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - delete
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"system:fluentd-gcp-scaler","namespace":"kube-system"},"rules":[{"apiGroups":["extensions"],"resources":["daemonsets"],"verbs":["get","patch"]},{"apiGroups":["scalingpolicy.kope.io"],"resources":["scalingpolicies"],"verbs":["get"]}]}
    creationTimestamp: "2020-01-11T06:01:02Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: system:fluentd-gcp-scaler
    namespace: kube-system
    resourceVersion: "360"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/system%3Afluentd-gcp-scaler
    uid: bf31e4f4-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    verbs:
    - get
    - patch
  - apiGroups:
    - scalingpolicy.kope.io
    resources:
    - scalingpolicies
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"system:pod-nanny","namespace":"kube-system"},"rules":[{"apiGroups":[""],"resources":["pods"],"verbs":["get"]},{"apiGroups":["extensions"],"resources":["deployments"],"verbs":["get","update"]}]}
    creationTimestamp: "2020-01-11T06:01:02Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: system:pod-nanny
    namespace: kube-system
    resourceVersion: "363"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/system%3Apod-nanny
    uid: bf42c709-3437-11ea-9cdc-42010a8001cf
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
  - apiGroups:
    - extensions
    resources:
    - deployments
    verbs:
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"typha-cpha","namespace":"kube-system"},"rules":[{"apiGroups":[""],"resources":["configmaps"],"verbs":["get"]},{"apiGroups":["apps","extensions"],"resources":["deployments/scale"],"verbs":["get","update"]}]}
    creationTimestamp: "2020-01-22T17:44:03Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: typha-cpha
    namespace: kube-system
    resourceVersion: "31420445"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/typha-cpha
    uid: c78fd225-3d3e-11ea-96d3-42010a80017a
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
  - apiGroups:
    - apps
    - extensions
    resources:
    - deployments/scale
    verbs:
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2020-01-18T00:05:48Z"
    labels:
      app: openfaas
      chart: openfaas-5.4.1
      component: faas-controller
      heritage: Helm
      release: openfaas
    name: openfaas-controller
    namespace: openfaas-fn
    resourceVersion: "2007021"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/openfaas-fn/roles/openfaas-controller
    uid: 48237733-3986-11ea-b115-42010a8001d6
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
  - apiGroups:
    - extensions
    - apps
    resources:
    - deployments
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - namespaces
    - endpoints
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2020-01-18T00:05:48Z"
    labels:
      app: openfaas
      chart: openfaas-5.4.1
      component: prometheus
      heritage: Helm
      release: openfaas
    name: openfaas-prometheus
    namespace: openfaas
    resourceVersion: "2007022"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/openfaas/roles/openfaas-prometheus
    uid: 482cb685-3986-11ea-b115-42010a8001d6
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
