apiVersion: v1
items:
- apiVersion: v1
  data:
    foo1: bar1
    foo2: bar2
  kind: ConfigMap
  metadata:
    creationTimestamp: "2020-01-11T21:42:29Z"
    name: my-config-2
    namespace: book
    resourceVersion: "196818"
    selfLink: /api/v1/namespaces/book/configmaps/my-config-1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
