/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../kubevious/src/logger.js                                                                   ***/

var config = {
    pretty: true
}

if (process.env.LOG_TO_FILE) {
    config.enableFile = true;
    config.cleanOnStart = true;
}

const logger = require('the-logger').setup('kubevious', config);
logger.level = 'debug';

module.exports = logger;