/*** UNDER NO CIRCUMSTANCES DO NOT EDIT THIS FILE. THIS FILE IS COPIED                                    ***/
/*** FROM OSS UI. ANY CHANGES TO BE MADE IN KUBEVIOUS OSS UI.                                             ***/
/*** SOURCE: ../ui/src/src/utils/naming-utils.js                                                          ***/

export function splitDn(dn) {
    var parts = [];

    var ch = null;
    var token = '';
    var parsingKind = true;
    var parsingNaming = true;
    for (var i = 0; i < dn.length; i++) {
        var skipAdd = false;
        ch = dn.charAt(i);
        if (parsingKind) {
            if (ch === '-') {
                parsingKind = false;
            } else if (ch === '/') {
                skipAdd = true;
                parts.push(token);
                token = '';
            }
        } else {
            if (parsingNaming) {
                if (ch === ']') {
                    parsingNaming = false;
                }
            } else {
                if (ch === '[') {
                    parsingNaming = true;
                } else if (ch === '/') {
                    skipAdd = true;
                    parts.push(token);
                    token = '';
                }
            }
        }

        if (!skipAdd) {
            token += ch;
        }
    }

    if (token.length > 0) {
        parts.push(token);
    }

    return parts;
}

export function parseRn(rn) {
    var index = rn.indexOf('-');
    if (index === -1) {
        return {
            rn: rn,
            kind: rn,
            name: null,
        };
    }
    return {
        rn: rn,
        kind: rn.substr(0, index),
        name: rn.substr(index + 2, rn.length - (index + 3)),
    };
}

export function parseDn(dn) {
    var parts = splitDn(dn);
    return parts.map(x => parseRn(x));
}

export function makeDn(parentDn, childRn) {
    if (!parentDn) {
        return childRn;
    }
    return parentDn + '/' + childRn;
}